### ISSUE TITLE
Needs additional access_token error handling in generate_token()

### ISSUE THREAD

**Issue by bwmetz** [CiscoSecurity/tr-04-get-dispositions#2]
These two lines do not gracefully deal with token generation failures:

    response_json = response.json()
    access_token = response_json['access_token']

For example, the following JSON response is received using the defaults:

`
    {'error': 'invalid_client', 'error_description': 'unknown client', 'error_uri': 'https://tools.ietf.org/html/rfc6749#section-5.2'}
`

Which in turn produces the following unhandled exceptions chain:

`
Traceback (most recent call last):
  File "get_dispositions.py", line 38, in get_token
    with open('threat_response_token', 'r') as token_file:
FileNotFoundError: [Errno 2] No such file or directory: 'threat_response_token'
`

During handling of the above exception, another exception occurs as a result:

`
Traceback (most recent call last):
  File "get_dispositions.py", line 130, in <module>
    main()
  File "get_dispositions.py", line 113, in main
    response = query(observable)
  File "get_dispositions.py", line 100, in query
    response = check_auth(inspect, observable)
  File "get_dispositions.py", line 89, in check_auth
    response = function(param)
  File "get_dispositions.py", line 51, in inspect
    access_token = get_token()
  File "get_dispositions.py", line 43, in get_token
    generate_token()
  File "get_dispositions.py", line 27, in generate_token
    access_token = response_json['access_token']
KeyError: 'access_token'
`

**Comment by bwmetz** [comment]
Errors reported above were observed running Python 3.7.4

**Comment by maugertg** [comment]
Good catch! The issue was caused by a change in the API response codes when the credentials are wrong. The [unauthorized](https://github.com/CiscoSecurity/tr-04-get-dispositions/blob/afb63805e9bbaa215a8044f80c705499699e54c7/get_dispositions.py#L77) function has been updated to account for this.

When using an invalid CLIENT_ID or CLIENT_PASSWORD you should now see the following output: 
```
Unable to generate new token!
Check your CLIENT_ID and CLIENT_PASSWORD
```
